In [69]:
from sklearn.linear_model import LogisticRegression
import numpy as np

X = np.array([[1, 2], [2, 1], [3, 4], [4, 3], [7, 11], [8, 14]])
y = np.array([1, 1, 0, 0, 2, 2])
N=len(X)
ds=np.append(X,y.reshape(N,1),1)
print(ds)


[[ 1  2  1]
 [ 2  1  1]
 [ 3  4  0]
 [ 4  3  0]
 [ 7 11  2]
 [ 8 14  2]]


In [70]:
classes=list(set(y))
ds=X
for i in classes:
  yy=list()
  for j in y:
    if j==i:
      yy.append(1)
    else:
      yy.append(0)
  yy=np.array(yy)
  ds=np.append(ds,yy.reshape(N,1),1)

In [71]:
ds

array([[ 1,  2,  0,  1,  0],
       [ 2,  1,  0,  1,  0],
       [ 3,  4,  1,  0,  0],
       [ 4,  3,  1,  0,  0],
       [ 7, 11,  0,  0,  1],
       [ 8, 14,  0,  0,  1]])

In [72]:
models=list()
for i in range(3):
  lr_model=LogisticRegression()
  lr_model.fit(ds[:,0:2],ds[:,2+i])
  models.append(lr_model)

In [73]:
#models[0].coeff_
#models[0].intercept_
tt=np.array([[1,2]])
tx=np.array([[1,2]])
np.sum(tt*tx)+np.array([[1]])


array([[6]])

In [74]:
def prob(z):
  totl=np.sum(np.exp(z))
  y_pred=list()
  for i in z:
    y_pred.append(np.exp(i)/totl)
  #y_pred=np.array(y_pred)
  return y_pred
  

In [75]:
def predict(X,models):
  z=list()
  for i in range(3):
    z.append(np.sum(models[i].coef_*X)+models[i].intercept_)
  z=np.array(z)

  y_pred=prob(z)

  return y_pred.index(max(y_pred))


In [77]:
X=np.array([8,16])
predict(X,models)

2